services:
  - type: web
    name: mamou-shopping
    env: php
    plan: free
    buildCommand: |
      # Désactiver Apache s'il est actif
      which apache2 && sudo service apache2 stop || true
      which apache2 && sudo systemctl disable apache2 || true
      
      # Configurations Laravel
      chmod -R 755 storage bootstrap/cache
      composer install --no-dev --optimize-autoloader --no-interaction
      php artisan optimize:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 10000