services:
  - type: web
    name: mamou-shopping
    env: php
    plan: free
    buildCommand: |
      # 1. ARRÊTER ET DÉSACTIVER APACHE COMPLÈTEMENT
      echo "🛑 Arrêt et suppression d'Apache..."
      sudo systemctl stop apache2 || true
      sudo systemctl disable apache2 || true
      sudo apt-get remove --purge apache2 apache2-utils apache2-bin -y || true
      sudo apt-get autoremove -y || true
      
      # 2. Configurations Laravel
      echo "🚀 Configuration de Laravel..."
      chmod -R 755 storage bootstrap/cache
      composer install --no-dev --optimize-autoloader --no-interaction
      php artisan key:generate --force
      php artisan optimize:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
    startCommand: php artisan serve --port=$PORT --host=0.0.0.0
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 10000