services:
  - type: web
    name: mamou-shopping
    env: php
    plan: free
    buildCommand: |
      # Copier la configuration Apache
      sudo cp apache.conf /etc/apache2/sites-available/000-default.conf
      # Activer mod_rewrite
      sudo a2enmod rewrite
      # Redémarrer Apache
      sudo service apache2 restart
      # Permissions Laravel
      chmod -R 755 storage bootstrap/cache
      composer install --no-dev --optimize-autoloader
      php artisan optimize:clear
    startCommand: |
      # Démarrer Apache en foreground
      apache2ctl -D FOREGROUND
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false