services:
  - type: web
    name: mamoushopping
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:WaICOXcD4dlMJNNUW8mZG0zo60Rgk+I9AYtizj/kK7k=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mamoushopping.onrender.com
