services:
  - type: web
    name: mamou-shopping
    env: php
    plan: free
    buildCommand: |
      # Désactiver Apache définitivement
      sudo systemctl disable apache2 || true
      sudo service apache2 stop || true
      
      # Configurations Laravel
      chmod -R 755 storage bootstrap/cache
      composer install --no-dev --optimize-autoloader --no-interaction
      php artisan optimize:clear
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      
      # Rendre le script executable
      chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: PORT
        value: 10000